#!/usr/bin/env python3
"""
sync_template.py — package template.weekly.html for the browser builder.

    python3 sync_template.py

Writes template.js, which does nothing but assign the template source to
window.WEEKLY_TEMPLATE so builder.html can build a page without Python.

Run this every time template.weekly.html changes, or builder.html will
quietly keep generating pages from the previous design.
"""

import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "template.weekly.html")
DEST = os.path.join(HERE, "template.js")

with open(SRC, encoding="utf-8") as fh:
    template = fh.read()

digest = hashlib.sha256(template.encode("utf-8")).hexdigest()[:12]

with open(DEST, "w", encoding="utf-8") as fh:
    fh.write("/* Generated by sync_template.py — do not edit.\n")
    fh.write("   Source: template.weekly.html  sha256:%s  %d bytes */\n" % (digest, len(template)))
    fh.write("window.WEEKLY_TEMPLATE = %s;\n" % json.dumps(template))
    fh.write("window.WEEKLY_TEMPLATE_HASH = %s;\n" % json.dumps(digest))

print("wrote %s (%.0f KB, template sha256:%s)" % (DEST, os.path.getsize(DEST) / 1024.0, digest))
